import bcrypt from "bcryptjs";
import { SignJWT, jwtVerify } from "jose";
import { parse as parseCookieHeader } from "cookie";
import type { Request } from "express";
import { ENV } from "./_core/env";
import { createEmailUser, getEmailUserByEmail, getEmailUserById, updateEmailUserLastSignedIn, updateEmailUserPassword, getValidResetToken, markResetTokenUsed } from "./db";
import type { EmailUser } from "../drizzle/schema";

const EMAIL_COOKIE_NAME = "email_session";
const SALT_ROUNDS = 10;
const ONE_YEAR_MS = 1000 * 60 * 60 * 24 * 365;

function getSessionSecret() {
  return new TextEncoder().encode(ENV.cookieSecret);
}

/**
 * Hash a plaintext password with bcrypt.
 */
export async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, SALT_ROUNDS);
}

/**
 * Compare a plaintext password against a bcrypt hash.
 */
export async function comparePassword(password: string, hash: string): Promise<boolean> {
  return bcrypt.compare(password, hash);
}

/**
 * Register a new email user. Returns the new user ID.
 * Throws if email already exists.
 */
export async function registerEmailUser(data: {
  email: string;
  password: string;
  nickname: string;
  realName?: string;
  company?: string;
  phone?: string;
}): Promise<number> {
  // Check if email already exists
  const existing = await getEmailUserByEmail(data.email);
  if (existing) {
    throw new Error("该邮箱已被注册");
  }

  const passwordHash = await hashPassword(data.password);
  return createEmailUser({
    email: data.email,
    passwordHash,
    nickname: data.nickname,
    realName: data.realName,
    company: data.company,
    phone: data.phone,
  });
}

/**
 * Validate password strength:
 * - At least 8 characters
 * - Contains uppercase letter
 * - Contains lowercase letter
 * - Contains digit
 */
export function validatePasswordStrength(password: string): { ok: boolean; message?: string } {
  if (password.length < 8) {
    return { ok: false, message: "密码至少8位" };
  }
  if (!/[A-Z]/.test(password)) {
    return { ok: false, message: "密码需包含至少一个大写字母" };
  }
  if (!/[a-z]/.test(password)) {
    return { ok: false, message: "密码需包含至少一个小写字母" };
  }
  if (!/[0-9]/.test(password)) {
    return { ok: false, message: "密码需包含至少一个数字" };
  }
  return { ok: true };
}

/**
 * Change password for a logged-in user.
 * Verifies old password, validates new password strength, then updates.
 */
export async function changePassword(userId: number, oldPassword: string, newPassword: string): Promise<void> {
  const user = await getEmailUserById(userId);
  if (!user) {
    throw new Error("用户不存在");
  }

  const valid = await comparePassword(oldPassword, user.passwordHash);
  if (!valid) {
    throw new Error("原密码错误");
  }

  const strength = validatePasswordStrength(newPassword);
  if (!strength.ok) {
    throw new Error(strength.message!);
  }

  const newHash = await hashPassword(newPassword);
  await updateEmailUserPassword(userId, newHash);
}

/**
 * Reset password using a reset code (generated by admin).
 */
export async function resetPasswordWithCode(email: string, resetCode: string, newPassword: string): Promise<void> {
  const strength = validatePasswordStrength(newPassword);
  if (!strength.ok) {
    throw new Error(strength.message!);
  }

  const token = await getValidResetToken(email, resetCode);
  if (!token) {
    throw new Error("重置码无效或已过期");
  }

  const user = await getEmailUserByEmail(email);
  if (!user) {
    throw new Error("用户不存在");
  }

  const newHash = await hashPassword(newPassword);
  await updateEmailUserPassword(user.id, newHash);
  await markResetTokenUsed(token.id);
}

/**
 * Authenticate an email user by email + password.
 * Returns the user if successful, throws on failure.
 */
export async function loginEmailUser(email: string, password: string): Promise<EmailUser> {
  const normalized = email.trim();
  const user =
    (await getEmailUserByEmail(normalized)) ||
    (normalized === ENV.adminUsername ? await getEmailUserByEmail(`${normalized}@openit.cc`) : undefined);
  if (!user) {
    throw new Error("Invalid username or password");
  }

  const valid = await comparePassword(password, user.passwordHash);
  if (!valid) {
    throw new Error("Invalid username or password");
  }

  // Update last signed in
  await updateEmailUserLastSignedIn(user.id);

  return user;
}

/**
 * Create a JWT session token for an email user.
 */
export async function createEmailSessionToken(user: EmailUser): Promise<string> {
  const secretKey = getSessionSecret();
  const issuedAt = Date.now();
  const expirationSeconds = Math.floor((issuedAt + ONE_YEAR_MS) / 1000);

  return new SignJWT({
    emailUserId: user.id,
    email: user.email,
    nickname: user.nickname,
    type: "email",
  })
    .setProtectedHeader({ alg: "HS256", typ: "JWT" })
    .setExpirationTime(expirationSeconds)
    .sign(secretKey);
}

/**
 * Verify an email session from the request cookie.
 * Returns the EmailUser or null.
 */
export async function verifyEmailSession(req: Request): Promise<EmailUser | null> {
  const cookieHeader = req.headers.cookie;
  if (!cookieHeader) return null;

  const cookies = parseCookieHeader(cookieHeader);
  const token = cookies[EMAIL_COOKIE_NAME];
  if (!token) return null;

  try {
    const secretKey = getSessionSecret();
    const { payload } = await jwtVerify(token, secretKey, { algorithms: ["HS256"] });

    if (payload.type !== "email" || typeof payload.emailUserId !== "number") {
      return null;
    }

    const user = await getEmailUserById(payload.emailUserId);
    return user || null;
  } catch (error) {
    return null;
  }
}

export { EMAIL_COOKIE_NAME };
